export const NICHES = [
  "Academias",
  "Advogados",
  "Barbearias",
  "Clínicas Médicas",
  "Construção Civil",
  "Contabilidades",
  "Dentistas",
  "Depilação",
  "Escolas",
  "Espaços de Bronzeamento",
  "Estética Automotiva",
  "Farmácias",
  "Imobiliárias",
  "Lojas de Roupas",
  "Oficinas Mecânicas",
  "Papelarias",
  "Pet Shops",
  "Pizzarias",
  "Psicólogas",
  "Restaurantes",
  "Salões de Beleza",
  "Sorveterias",
  "Veterinários"
].sort();

export const LOCATIONS = [
  "Aracaju, SE",
  "Belém, PA",
  "Belo Horizonte, MG",
  "Boa Vista, RR",
  "Brasília, DF",
  "Campinas, SP",
  "Campo Grande, MS",
  "Cuiabá, MT",
  "Curitiba, PR",
  "Florianópolis, SC",
  "Fortaleza, CE",
  "Goiânia, GO",
  "João Pessoa, PB",
  "Macapá, AP",
  "Maceió, AL",
  "Manaus, AM",
  "Natal, RN",
  "Palmas, TO",
  "Porto Alegre, RS",
  "Porto Velho, RO",
  "Recife, PE",
  "Rio Branco, AC",
  "Rio de Janeiro, RJ",
  "Salvador, BA",
  "São Luís, MA",
  "São Paulo, SP",
  "Teresina, PI",
  "Vitória, ES",
  "Santos, SP",
  "Ribeirão Preto, SP"
].sort();
